### ISSUE TITLE
Build for v0.5.6 failed

### ISSUE THREAD

**Issue by kmnhan** [conda-forge/igor2-feedstock#2]
### Comment:

Hello, thanks for maintaining this feedstock!

It appears that the most recent build has failed and 0.5.6 has not been uploaded. Looking at https://github.com/conda-forge/status/issues/166 and https://github.com/conda-forge/status/issues/174, it looks like a simple rerun should get it working.

Update:

@janberges, I'm leaving a mention because I'm unsure whether new feedstock issues notify the maintainers. I apologize for any inconvenience I might have caused.

**Comment by janberges** [comment]
Thanks for letting me know and for suggesting a solution! I have triggered the rebuild, and the new version should be available soon.

It was indeed necessary to mention me since I was not watching this repository, sorry. Now I should receive notifications about all activity.
